# Generated by Django 5.0.1 on 2024-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupon_name_coupon_code'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupons',
            field=models.ManyToManyField(to='coupon.coupon'),
        ),
    ]
