# Generated by Django 5.0.1 on 2024-02-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='building_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
