# Generated by Django 5.0.1 on 2024-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='jibun_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
