# Generated by Django 5.0.1 on 2024-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='실제 주문시 사용하는 쿠폰 코드', max_length=50, unique=True)),
                ('content', models.CharField(help_text='쿠폰 설명', max_length=255)),
                ('minimum_order_price', models.PositiveIntegerField(default=0, help_text='쿠폰 사용 최소 금액')),
                ('discount_price', models.PositiveIntegerField(default=0, help_text='쿠폰 할인 금액')),
                ('expiration_date', models.DateTimeField(help_text='쿠폰 유효 기간')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
