# Generated by Django 5.0.1 on 2024-03-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
    ]
