# Generated by Django 5.0.1 on 2024-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupon_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
