# Generated by Django 5.0.1 on 2024-01-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupon_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='deleted_at',
            new_name='expiration_date',
        ),
    ]
