# Generated by Django 5.0.2 on 2024-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_alter_coupon_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='실제 주문시 사용하는 쿠폰 코드', max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='content',
            field=models.CharField(help_text='쿠폰 설명', max_length=255),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.PositiveIntegerField(default=0, help_text='쿠폰 할인 금액'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(help_text='쿠폰 유효 기간(발급 이후 +2일)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_price',
            field=models.PositiveIntegerField(default=0, help_text='쿠폰 사용 최소 금액'),
        ),
    ]
