# Generated by Django 5.0.2 on 2024-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_alter_coupon_code_alter_coupon_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='실제 주문시 사용하는 쿠폰 코드', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(help_text='쿠폰 유효 기간'),
        ),
    ]
