# Generated by Django 5.0.1 on 2024-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/%Y/%m/%d'),
        ),
    ]
