# Generated by Django 5.0.1 on 2024-04-15 02:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_blogimage_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='BlogImage',
            new_name='PostImage',
        ),
    ]
