# Generated by Django 5.0.1 on 2024-04-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_rename_blog_post_rename_blogimage_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='blog',
            new_name='post',
        ),
    ]
