# Generated by Django 5.0.1 on 2024-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_rename_blog_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(null=True, upload_to='community/%Y/%m/%d'),
        ),
    ]
