# Generated by Django 5.0.2 on 2024-04-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerComment',
        ),
    ]
