# Generated by Django 5.0.1 on 2024-03-31 01:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '대분류',
                'verbose_name_plural': '대분류',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.maincategory')),
            ],
            options={
                'verbose_name': '중분류',
                'verbose_name_plural': '중분류',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='매장 이름')),
                ('address', models.CharField(max_length=255, verbose_name='매장 주소')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^02?-?\\d{3,4}-?\\d{4}$')], verbose_name='매장 전화번호')),
                ('image', models.ImageField(blank=True, default='default_restaurant.png', null=True, upload_to='restaurant_image/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='매장 설명')),
                ('minimumOrderPrice', models.PositiveIntegerField(default=0, verbose_name='최소 주문 금액')),
                ('minimumPickupPrice', models.PositiveIntegerField(default=0, verbose_name=' 픽업 최소 주문 금액')),
                ('minDeliveryTime', models.PositiveSmallIntegerField(default=0, verbose_name='최소 배달 시간')),
                ('maxDeliveryTime', models.PositiveSmallIntegerField(default=0, verbose_name='최대 배달 시간')),
                ('minPickupTime', models.PositiveIntegerField(default=0, null=True, verbose_name='최소 픽업 시간')),
                ('orderCount', models.PositiveIntegerField(default=0, verbose_name='주문수')),
                ('reviewCount', models.PositiveIntegerField(default=0, verbose_name='리뷰수')),
                ('bookmarkCount', models.PositiveIntegerField(default=0, verbose_name='즐겨찾기수')),
                ('averageRating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='식당 평점')),
                ('packaging', models.BooleanField(default=False, verbose_name='포장 여부')),
                ('status', models.BooleanField(default=False, verbose_name='매장 운영 여부')),
                ('start', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 24), django.core.validators.MaxValueValidator(24)], verbose_name='영업 시작 시간')),
                ('end', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 36), django.core.validators.MaxValueValidator(36)], verbose_name='영업 마감 시간')),
                ('operatingTime', models.CharField(max_length=255, verbose_name='운영 시간 설명')),
                ('deliveryFee', models.PositiveIntegerField(default=0, verbose_name='배달 요금')),
                ('latitude', models.DecimalField(decimal_places=11, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('mainCategory', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mainCategory', to='restaurant.maincategory', verbose_name='매장 대분류')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='매장 소유자')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subCategory', to='restaurant.subcategory', verbose_name='매장 중분류')),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장',
            },
        ),
    ]
