# Generated by Django 5.0.1 on 2024-01-27 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^02?-?\\d{3,4}-?\\d{4}$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_image')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('minimumOrderPrice', models.IntegerField()),
                ('minDeliveryTime', models.DateTimeField(null=True)),
                ('maxDeliveryTime', models.DateTimeField(null=True)),
                ('orderCount', models.IntegerField(default=0)),
                ('reviewCouunt', models.IntegerField(default=0)),
                ('bookmarkCount', models.IntegerField(default=0)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 5), django.core.validators.MaxValueValidator(5.0)])),
                ('packaging', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('operatingTime', models.CharField(max_length=255)),
            ],
        ),
    ]
