# Generated by Django 5.0.1 on 2024-01-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='maxDeliveryTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='minDeliveryTime',
            field=models.TimeField(null=True),
        ),
    ]
