# Generated by Django 5.0.1 on 2024-03-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_maincategory_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='delivertyFee',
            new_name='deliveryFee',
        ),
    ]
