# Generated by Django 5.0.1 on 2024-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_maxdeliverytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='maxDeliveryTime',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='minDeliveryTime',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
