# Generated by Django 5.0.1 on 2024-02-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_maxdeliverytime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '대분류',
                'verbose_name_plural': '대분류',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mainCategory',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mainCategory', to='restaurant.maincategory'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.maincategory')),
            ],
            options={
                'verbose_name': '중분류',
                'verbose_name_plural': '중분류',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subCategory',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subCategory', to='restaurant.subcategory'),
        ),
    ]
