# Generated by Django 5.0.1 on 2024-02-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_maincategory_restaurant_maincategory_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subCategory', to='restaurant.subcategory'),
        ),
    ]
