# Generated by Django 5.0.2 on 2024-03-02 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 5), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
