# Generated by Django 5.0.2 on 2024-02-29 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.PositiveIntegerField(null=True)),
                ('food_name', models.CharField(max_length=100)),
                ('food_price', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('option_name', models.JSONField(default=dict, null=True)),
                ('option_price', models.JSONField(default=dict, null=True)),
                ('restaurant_id', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
