# Generated by Django 5.0.1 on 2024-02-04 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='created_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='created_hour',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
