# Generated by Django 5.0.2 on 2024-03-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_maincategory_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_image/menu/%Y/%m/%d')),
                ('is_main', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('option', 'Option'), ('radio', 'Radio')], default='option', max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.menu')),
            ],
        ),
    ]
