# Generated by Django 5.0.2 on 2024-03-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='type',
        ),
        migrations.AddField(
            model_name='menu',
            name='required_options_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MenuSelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_options', to='menu.menu')),
            ],
        ),
    ]
