# Generated by Django 5.0.1 on 2024-01-29 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('is_checked', models.BooleanField(default=False)),
                ('check_option', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.menu')),
            ],
        ),
    ]
