# Generated by Django 5.0.2 on 2024-03-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuoption',
            old_name='is_checked',
            new_name='is_required',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='check_option',
        ),
        migrations.AddField(
            model_name='menu',
            name='content',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='type',
            field=models.CharField(choices=[('option', 'Option'), ('radio', 'Radio')], default='option', max_length=10),
        ),
    ]
