# Generated by Django 5.0.1 on 2024-03-30 06:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0007_coupon_is_active_alter_coupon_code_and_more'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_written', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_list', models.JSONField(blank=True, default=dict)),
                ('option_list', models.JSONField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('deliveryman_request', models.TextField(blank=True, null=True)),
                ('required_options_count', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('credit_card', '신용 카드'), ('cash', '현금')], max_length=20)),
                ('deliver_address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deliver', models.BooleanField(default=True)),
                ('delivery_state', models.CharField(choices=[('waiting', '대기'), ('pickup_complete', '포장완료'), ('delivery_complete', '배달완료')], default='대기', max_length=20, verbose_name='포장배달 상태')),
                ('order_state', models.CharField(choices=[('order_complete', '주문완료'), ('payment_complete', '결제완료'), ('order_cancel', '주문취소'), ('payment_cancel', '결제취소')], default='주문완료', max_length=16, verbose_name='주문서 상태')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupon')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
