# Generated by Django 5.0.1 on 2024-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='required_options_count',
        ),
        migrations.AddField(
            model_name='order',
            name='disposable_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='soption_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
