# Generated by Django 5.0.2 on 2024-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_id_order_required_options_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryman_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
