# Generated by Django 5.0.1 on 2024-04-11 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_coupon_is_active_alter_coupon_code_and_more'),
        ('order', '0004_order_estimate_time'),
        ('restaurant', '0002_alter_restaurant_latitude_alter_restaurant_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'restaurant'], name='order_order_user_id_55446d_idx'),
        ),
    ]
