# Generated by Django 5.0.2 on 2024-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_delivery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_written',
            field=models.BooleanField(default=False),
        ),
    ]
