# Generated by Django 5.0.2 on 2024-03-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_review_written'),
        ('order', '0008_order_latitude_order_longitude'),
    ]

    operations = [
    ]
