# Generated by Django 5.0.2 on 2024-03-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='soption_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
