# Generated by Django 5.0.2 on 2024-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_soption_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disposable_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
