# Generated by Django 5.0.2 on 2024-03-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_disposable_request_order_restaurant_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='required_options_count',
        ),
    ]
